pipeline {
    agent any

    parameters {
        string(defaultValue: "develop", description: '', name: 'branch_name_provided')
    }

    stages {
        stage('Build') {
            steps {
                // checkout scm
                // git([url: 'git://example.com/amazing-project.git', branch: 'master'])
                // sh 'git clone https://github.com/PALMDEV/drproject.git'
                
                echo 'Building..'
                







                

                
                
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                // sh '0'
                // error('stop on test')

                

            }
            // post {
            //     failure {
            //         // echo "error"
                    
            //         // error('least')
                    

            //     }
            // }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        failure {
            
            mail to: 'team@example.com', subject: 'Pipeline failed', body: "${env.BUILD_URL}"
        }
    }

}